---
name: base-site-migrator
---
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    Dynamic\TemplateConfig\Model\NavigationColumn: Dynamic\Base\Model\NavigationColumn
    Dynamic\TemplateConfig\Model\NavigationGroup: Dynamic\Base\Model\NavigationGroup
    Dynamic\TemplateConfig\Model\SocialLink: Dynamic\Base\Model\SocialLink

Dynamic\Base\Model\SocialLink:
  extensions:
    - Dynamic\BaseMigrator\Extension\ModelMigrationDataExtension

Dynamic\Base\Model\NavigationColumn:
  extensions:
    - Dynamic\BaseMigrator\Extension\ModelMigrationDataExtension

Dynamic\Base\Model\NavigationGroup:
  extensions:
    - Dynamic\BaseMigrator\Extension\ModelMigrationDataExtension

Dynamic\TemplateConfig\Model\TemplateConfigSetting:
  extensions:
    - Dynamic\TemplateConfig\ORM\BrandingDataExtension
